all:
	g++ -D_DEBUG -O3 -Wall -Wextra -o bin/server_dbg server.cpp
	g++ -D_DEBUG -O3 -Wall -Wextra -o bin/client_dbg client.cpp
	g++ -O3 -static -o bin/server server.cpp
	g++ -O3 -static -o bin/client client.cpp
